version: '3.8'

services:
  telegram-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - PORT=5000
    volumes:
      - ./file_storage.db:/app/file_storage.db
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Alternative: Polling mode
  telegram-bot-polling:
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./file_storage.db:/app/file_storage.db
      - ./logs:/app/logs
    command: ["python", "main.py"]
    restart: unless-stopped
    profiles:
      - polling

volumes:
  bot_data:
    driver: local